#!/bin/zsh
rb=$(($RANDOM % 256))
re=$(($RANDOM % 256))
gb=$(($RANDOM % 256))
ge=$(($RANDOM % 256))
bb=$(($RANDOM % 256))
be=$(($RANDOM % 256))

virgin=1
while [[ $virgin = 1 ]] || read foo 
do
  virgin=0
  if [[ $foo == content ]] {
    rb=$(($RANDOM % 256))
    re=$(($RANDOM % 256))
    gb=$(($RANDOM % 256))
    ge=$(($RANDOM % 256))
    bb=$(($RANDOM % 256))
    be=$(($RANDOM % 256))
  }
  if [[ -e content && -e index ]] {
    content=`cat content`
    len=$(echo $content | wc -l)
    index=(`cat index`)
    index=$((index % $len))
    if [[ index < 0 ]] {
      index=$((index + $len))
    }
    # ans=$content[$((index + 1))]
    ans=""
    item=0
    echo $content | while read cur_content
    do
      item=$(($item + 1))
      r=$(($rb.0 + ($re.0 - $rb.0) / $len.0 * $item.0))
      g=$(($gb.0 + ($ge.0 - $gb.0) / $len.0 * $item.0))
      b=$(($bb.0 + ($be.0 - $bb.0) / $len.0 * $item.0))
      r=$(printf "%02x" r)
      g=$(printf "%02x" g)
      b=$(printf "%02x" b)
      if [[ $((item - 1)) = $index ]] {
        item_content=$cur_content
        ans+=" %{o#$r$g$b}%{+o}$item_content%{o-}%{-o}"
      } else {
        item_content=$cur_content
        ans+=" %{u#$r$g$b}%{+u}$item_content[1,2]%{u-}%{-u}"
      }
    done
    # echo $content
    # echo $index
    # echo $content[$index]
    echo $ans
  }
done
