#!/bin/zsh
cd $(dirname $0)

while true; do
  if ! [[ -e index ]] {
    echo 1 > index
    # export WUNDERLIST_INDEX=1
  }
  content=`wunderline list inbox || echo error`
  if [[ content != error ]] {
    content=${content//☆/}
    content=$(echo $content | awk '{$1=$1};1')
    content=${content// /\\ }
    content=`echo $content | tail -n +2`
    content_before=$(cat content)
    if [[ ${content//\n/} != ${content_before//\n/} ]] {
      echo $content > content
    }
  } else {
    echo error
  }
  sleep 60
done
# export WUNDERLIST_CONTENT=$content
# echo $WUNDERLIST_CONTENT
# echo $content
